### ISSUE TITLE
Issue while trying to run in windows.

### ISSUE THREAD

**Issue by namanshenoy** [sjmcdowall/tems-examples#1]
Node version : v8.0.0
Windows: Embedded Standard
NPM Install runs fine, no errors. One warning related to webpack ^2.xx
npm start causes error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tems-examples-node@1.0.0~prestart: tems-examples-node@1.0.0
6 verbose lifecycle tems-examples-node@1.0.0~prestart: unsafe-perm in lifecycle true
9 silly lifecycle tems-examples-node@1.0.0~prestart: Args: [ '/d /s /c', 'test -d node_modules || npm install' ]
10 silly lifecycle tems-examples-node@1.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle tems-examples-node@1.0.0~start: tems-examples-node@1.0.0
12 verbose lifecycle tems-examples-node@1.0.0~start: unsafe-perm in lifecycle true
15 silly lifecycle tems-examples-node@1.0.0~start: Args: [ '/d /s /c',
15 silly lifecycle   'cross-env NODE_ENV=development node --harmony-async-await main' ]
16 silly lifecycle tems-examples-node@1.0.0~start: Returned: code: 9  signal: null
17 info lifecycle tems-examples-node@1.0.0~start: Failed to exec start script
18 verbose stack Error: tems-examples-node@1.0.0 start: `cross-env NODE_ENV=development node --harmony-async-await main`
18 verbose stack Exit status 9
18 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at EventEmitter.emit (events.js:213:7)
18 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at ChildProcess.emit (events.js:213:7)
18 verbose stack     at maybeClose (internal/child_process.js:887:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
19 verbose pkgid tems-examples-node@1.0.0
20 verbose cwd C:\Users\test\Documents\GitHub\tems-examples\node
21 verbose Windows_NT 6.1.7601
22 verbose argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 verbose node v8.0.0
24 verbose npm  v5.0.0
25 error code ELIFECYCLE
26 error errno 9
27 error tems-examples-node@1.0.0 start: `cross-env NODE_ENV=development node --harmony-async-await main`
27 error Exit status 9
28 error Failed at the tems-examples-node@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 9, true ]
```

**Comment by sjmcdowall** [comment]
I haven't had a chance to try this against Node V8/NPM 5 .. since it worked on Node V7.5 I'm a bit surprised it didn't work on Node V8 but who knows!  :)  It may take me a day or so to give it a whirl -- but thanks for checking it out.

**Comment by namanshenoy** [comment]
I'll downgrade to 7.5 and see how it works :)

**Comment by namanshenoy** [comment]
Works in 7.5 :)
